### ISSUE TITLE
Stop using tabs in generated parsers

### ISSUE THREAD

**Issue by treeowl** [haskell/happy#24]
The title pretty much speaks for itself—using tabs for layout is usually not the greatest idea, so Happy shouldn't be producing code that does so. The simplest way to do this is probably to replace `\t` with eight literal spaces everywhere it appears in the code generator source. The clean way is probably to add a function `tabIn = ("        "++)`

**Comment by andreasabel** [comment]
This issue is still open, the current workaround is to switch off _all_ warnings via `{-# OPTIONS_GHC -w #-}` (crude).
I would also vouch for emitting spaces instead of tab characters, but 2 spaces per tab are enough for my taste.

**Comment by sgraf812** [comment]
> the current workaround is to switch off all warnings via {-# OPTIONS_GHC -w #-} (crude).

What is the alternative? We *could* just pass  `{-# OPTIONS_GHC -Wno-warn-tabs #-}` or whatever.
Then we would again see warnings in user-written Haskell code in .y files (which are *supposed* to be small...).
However, what if a new GHC version emits more warnings, such as the new `x-partial` warnings for use of `head` and `tail`?
Then we might again get warnings in generated code and that's quite annoying.

In the meantime, #291 generates code with 2 spaces instead of tabs.

**Comment by andreasabel** [comment]
> What is the alternative?

Make positive list, i.e.:
Put a long list of warning flags like `{-# OPTIONS_GHC -Wwarn-tabs #-}` in the preamble that we know we wouldn't trigger.

**Comment by ulidtko** [comment]
... Please disregard the comments I made 10 years ago!

They're surprising even to me now. 😅
