### ISSUE TITLE
Merge `happy-*` library packages into a single `happy` library component

### ISSUE THREAD

**Issue by sgraf812** [haskell/happy#292]
Triggered by the discussion in https://github.com/haskell/happy/issues/288, we found that it would be preferable to merge all `happy-*` library packages into the library component associated with the `happy` executable. The reasons are:

* Less maintenance overhead compared to the status quo (see #288).
* `happy` does not have many dependencies, so there is almost no added value of splitting it into several libraries. For example, `happy-backend-lalr` does not take much longer to compile than `happy-grammar`. 
* Multiple public library components as in Cabal 3.0 allow to retain the split, ~~but none of the compilation time benefits apply because [all components are built anyway](https://github.com/haskell/happy/issues/288#issuecomment-2348942466)~~ Edit: wrong according to @phadej; see below. However, multiple public components might also be less well supported by `stack` and `nix`.

I will prepare a PR.

**Comment by phadej** [comment]
> all components are built anyway.
 
 Wrong. I didn't say that. I said *solved for*.

**Comment by Ericson2314** [comment]
I am very much against this for the reasons I wrote in https://github.com/haskell/happy/pull/293#pullrequestreview-2303292028 (I keep on seeing the PRs first before the issues, sorry.)

**Comment by Ericson2314** [comment]
> concrete evidence 

Let me flip this around. If we do multiple libraries in a single package, what evidence is there for concrete overhead? If no one wants to use new features like multi-package `nix repl`, multiple libraries per package, etc. what is even the point of these features being developed? Someone has to be the guinea pig.

Now, because we've had the multiple libraries, things have not bled back together. So I have no evidence of this happening in happy since the split, nor should I, because the remedy is in place. However, I've seen numerous examples of the architecture going to shit in many other projects, including GHC, projects at work, etc. etc. I can't share the work ones publicly but you can ask me privately if you like.

I always hoped that `happy` and `alex` could be the pioneer for doing things "the right way", i.e. with internal component boundary enforcement. Yes, they are smaller projects, but that makes it easier to demonstrate the viability of things. If we try shipping a multiple-libraries-per-package release and shit hits the fan, then we should gather up those bug s and get the HF to coordinate them being fixed.

**Comment by sgraf812** [comment]
Closed in favor of the design described in https://github.com/haskell/happy/issues/288#issuecomment-2350867172.
